#! /bin/bash
echo "BuildTime;SearchTime;Nthreads;data_type;points_found">result_mpi_local.csv
./make_dirs

make
for ((k = 0; k < 4; k += 1))
do
for j in d f 1000 10000 100000
do
for ((i = 1; i <= 32; i *= 2))
do
mpiexec -n $i ./prog $j 10
done
done
done

for ((k = 0; k < 4; k += 1))
do
for j in d f 1000 10000 100000
do
for i in 3 7 15 31
do
mpiexec -n $i ./prog $j 10
done
done
done
