#! /bin/bash
#echo "BuildTime;SearchTime;Nthreads;data_type">result_mpi_polus.csv
./make_dirs

make
for ((k = 0; k < 4; k += 1))
do
for j in d f 100000 1000000 10000000
do
for ((i = 1; i <= 32; i += 1))
do
mpisubmit.pl -p $i -w 00:30 --stdout ./out_files/$j/$i.out --stderr ./err_files/$j/$i.err ./prog -- $j 10
done
done
done
